name: "hap.py"
description: Comparison of vcf files and calculating performance metrics following GA4GH defined best practices for benchmarking small variant call sets (ADD REF). Part of the hap.py suite by Illumina (see https://github.com/Illumina/hap.py/blob/master/doc/normalisation.md).
authors:
  - Nathan D. Olson
